language: java
script:
- cd ..
- git clone https://github.com/yasmin-aumeeruddy/action-test
- cd action-test
- mkdir -p instructions/guide-microprofile-opentracing
- rm -f instructions/guide-microprofile-opentracing/README.md
- javac GuideConverter.java
- java GuideConverter guide-microprofile-opentracing
- rm -f temp.adoc
- git checkout -b actions-mp-ot
- git config --global user.email "action@example.com"
- git config --global user.name "action"
- git add .
- java GuideConverter guide-microprofile-opentracing
- git commit -m "updated by github actions from guide-microprofile-opentracing"
- git push -u origin actions-mp-ot
